# Generated by Django 6.0.2 on 2026-02-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('department', models.CharField(blank=True, max_length=5, null=True)),
                ('avgcontime', models.IntegerField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=60, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hms_doctors_local',
            },
        ),
        migrations.CreateModel(
            name='DoctorTiming',
            fields=[
                ('slno', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('t1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('t2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hms_doctorstiming_local',
            },
        ),
        migrations.CreateModel(
            name='HospitalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(blank=True, max_length=150, null=True)),
                ('address1', models.CharField(blank=True, max_length=50, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hms_hospital_info',
            },
        ),
    ]
