# Generated by Django 6.0.2 on 2026-02-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('synced_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_department',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='doctortiming',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hospitalinfo',
            options={'managed': False},
        ),
    ]
