# Generated by Django 6.0.2 on 2026-03-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_department_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='hms_department_local',
        ),
    ]
