# Generated by Django 6.0.2 on 2026-03-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_department_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='hms_department',
        ),
        migrations.AlterModelTable(
            name='doctor',
            table='hms_doctors',
        ),
        migrations.AlterModelTable(
            name='doctortiming',
            table='hms_doctorstiming',
        ),
    ]
